-- =============================================================================
-- LIMPIEZA DE PROCEDIMIENTOS ALMACENADOS
-- (Se especifica la firma de argumentos para que el DROP sea inequívoco.)
-- =============================================================================
DROP PROCEDURE IF EXISTS modificar_rol_usuario(INTEGER, INTEGER) CASCADE;
DROP PROCEDURE IF EXISTS crear_rol(VARCHAR, VARCHAR) CASCADE;
DROP PROCEDURE IF EXISTS eliminar_rol(INTEGER) CASCADE;
DROP PROCEDURE IF EXISTS agregar_permiso_rol(INTEGER, INTEGER) CASCADE;
DROP PROCEDURE IF EXISTS eliminar_permiso_rol(INTEGER, INTEGER) CASCADE;
DROP FUNCTION IF EXISTS reporte_skus_retirados(INTEGER) CASCADE;

-- =============================================================================
-- LIMPIEZA DE ÍNDICES Y TABLAS
-- =============================================================================
DROP INDEX IF EXISTS usuario__IDXv1 CASCADE;
DROP INDEX IF EXISTS usuario__IDX CASCADE;
DROP INDEX IF EXISTS conciliacion_pago__IDXv1 CASCADE;
DROP INDEX IF EXISTS conciliacion_pago__IDX CASCADE;
DROP TABLE IF EXISTS historico_estatus CASCADE;
DROP TABLE IF EXISTS historial_post_venta CASCADE;
DROP TABLE IF EXISTS consumo_materia_prima CASCADE;
DROP TABLE IF EXISTS fpp_contrato CASCADE;
DROP TABLE IF EXISTS fase_prueba_produccion CASCADE;
DROP TABLE IF EXISTS conciliacion_pago CASCADE;
DROP TABLE IF EXISTS unidad_producto CASCADE;
DROP TABLE IF EXISTS despacho CASCADE;
DROP TABLE IF EXISTS orden_produccion CASCADE;
DROP TABLE IF EXISTS fc_cargo CASCADE;
DROP TABLE IF EXISTS detalle_prenomina CASCADE;
DROP TABLE IF EXISTS puja CASCADE;
DROP TABLE IF EXISTS subasta CASCADE;
DROP TABLE IF EXISTS orden_compra CASCADE;
DROP TABLE IF EXISTS prenomina CASCADE;
DROP TABLE IF EXISTS taxonomia CASCADE;
DROP TABLE IF EXISTS fase_prueba_diseno CASCADE;
DROP TABLE IF EXISTS historico_valor_mercado CASCADE;
DROP TABLE IF EXISTS dp_profesion CASCADE;
DROP TABLE IF EXISTS dp_categoria CASCADE;
DROP TABLE IF EXISTS autor_diseno CASCADE;
DROP TABLE IF EXISTS diseno_producto CASCADE;
DROP TABLE IF EXISTS contrato_horario CASCADE;
DROP TABLE IF EXISTS beneficio_contrato CASCADE;
DROP TABLE IF EXISTS asistencia CASCADE;
DROP TABLE IF EXISTS compra_online CASCADE;
DROP TABLE IF EXISTS contrato CASCADE;
DROP TABLE IF EXISTS categoria_categoria CASCADE;
DROP TABLE IF EXISTS categoria_producto CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS empleado CASCADE;
DROP TABLE IF EXISTS persona_juridica CASCADE;
DROP TABLE IF EXISTS metodo_pago CASCADE;
DROP TABLE IF EXISTS lote_materia_prima CASCADE;
DROP TABLE IF EXISTS materia_prima CASCADE;
DROP TABLE IF EXISTS fabrica CASCADE;
DROP TABLE IF EXISTS persona_natural CASCADE;
DROP TABLE IF EXISTS cargo CASCADE;
DROP TABLE IF EXISTS rol_permiso CASCADE;
DROP TABLE IF EXISTS historico_tasa_cambio CASCADE;
DROP TABLE IF EXISTS transporte CASCADE;
DROP TABLE IF EXISTS permiso CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS operacion_catalogo CASCADE;
DROP TABLE IF EXISTS pieza CASCADE;
DROP TABLE IF EXISTS molde CASCADE;
DROP TABLE IF EXISTS membresia CASCADE;
DROP TABLE IF EXISTS tipo_material CASCADE;
DROP TABLE IF EXISTS profesion CASCADE;
DROP TABLE IF EXISTS color CASCADE;
DROP TABLE IF EXISTS clasificacion_exclusividad CASCADE;
DROP TABLE IF EXISTS tipo_cuerpo CASCADE;
DROP TABLE IF EXISTS era_historica CASCADE;
DROP TABLE IF EXISTS departamento CASCADE;
DROP TABLE IF EXISTS horario CASCADE;
DROP TABLE IF EXISTS beneficio CASCADE;
DROP TABLE IF EXISTS estatus CASCADE;
DROP TABLE IF EXISTS moneda CASCADE;
DROP TABLE IF EXISTS lugar CASCADE;